FROM plincar/riscv-gnu-toolchain
EXPOSE 9999

ARG RISCV_PK=riscv-pk

# Install packages
RUN apt update && apt upgrade -y && \
    apt autoremove -y && apt clean && rm -rf /var/lib/apt/lists/*

# Build RISCV tools
WORKDIR "/root"
RUN git clone https://github.com/riscv-software-src/${RISCV_PK}.git && \
    cd ${RISCV_PK} && export RISCV=/opt/riscv/tools && \
    export PATH="/opt/riscv/gnu-toolchain/bin:$PATH"
    # ./build.sh && cd - && rm -rf ${RISCV_TOOLS}
