name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *' # 8 AM in UTC +8.

jobs:
  generate_tag:
    name: Generate Tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Tag
        id: t1
        uses: Kaven-Universe/github-action-current-date-time@v1.1.0
        with:
          format: "YYYY_MM_DD"
      - name: Get Release Name or Commit ID
        uses: tenhaus/get-release-or-tag@v2
        id: tag
  build_qemu_image:
    name: Build Qemu Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: plincar
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Qemu Docker Iamge
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.qemu
          push: true
          tags: plincar/riscv-qemu-emulator:latest, plincar/riscv-qemu-emulator:${{ generate_tag.steps.t1.outputs.time }}-${{ generate_tag.steps.tag.outputs.tag }}
  build_gnu_toolchain_image:
    name: Build GNU Toolchain Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: plincar
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Gnu Toolchain Docker Iamge
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.gnu.toolchain
          push: true
          tags: plincar/riscv-gnu-toolchain:latest, plincar/riscv-gnu-toolchain:${{ steps.t1.outputs.time }}-${{ steps.tag.outputs.tag }}
  build_llvm_toolchain_image:
    name: Build LLVM Toolchain Docker Image
    runs-on: ubuntu-latest
    needs: build_gnu_toolchain_image
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: plincar
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push LLVM Docker Iamge
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.llvm.toolchain
          push: true
          tags: plincar/riscv-llvm-toolchain:latest, plincar/riscv-llvm-toolchain:${{ steps.t1.outputs.time }}-${{ steps.tag.outputs.tag }}
