name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Release Name or Commit ID
        uses: tenhaus/get-release-or-tag@v2
        id: tag
      - name: Generate Tag
        id: t1
        uses: Kaven-Universe/github-action-current-date-time@v1.1.0
        with:
          format: "YYYY_MM_DD"
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: plincar
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Qemu
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.qemu
          push: true
          tags: plincar/riscv-qemu-emulator:latest, plincar/riscv-qemu-emulator:${{ steps.t1.outputs.time }}-${{ steps.tag.outputs.tag }}
      - name: Build and Push GNU Toolchain
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.gnu.toolchain
          push: true
          tags: plincar/riscv-gnu-toolchain-emulator:latest, plincar/riscv-gnu-toolchain-emulator:${{ steps.t1.outputs.time }}-${{ steps.tag.outputs.tag }}
